# Generated by Django 4.1.7 on 2023-03-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('hour', models.IntegerField()),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='weather.weather')),
            ],
        ),
    ]
